### PR TITLE
Refactor and improve documentation for BSD support

### PR DESCRIPTION
**Pull request by jakewilliami**
- [x] Refactor file structure and module names from macOS to BSD
  - [x] Expand support to all BSD-bases operating systems that [have compiler support](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os)<sup>1</sup>
  - [x] Update README documentation and docstrings accordingly 

<sup>1</sup>Note that while Bitrig is very similar to OpenBSD, it is [no longer supported by Rust](https://github.com/rust-lang/rust/issues/60743), so we cannot support it here.

Next steps will be to (1) ensure that an unsupported OS is handled correctly [as per previous comment](https://github.com/EstebanBorai/local-ip-address/pull/85#issuecomment-1312857382), and (2) add tests for FreeBSD.  These can be implemented in a separate PR.

### CODE REVIEW

**Comment by jakewilliami** [comment]
@EstebanBorai a question: while we can enable `cfg` attributes for all BSD-based operating systems supported by Rust, it may not be feasible to test on all of these (though of course we can see how we get on).  If it is, for example, only feasibly to test on FreeBSD, should we still claim to support other *BSD operating systems, or should we remove the `cfg` attributes entirely?

**Comment by jakewilliami** [comment]
By the way, while researching BSD-based operating systems that Rust supports, I found that [Tokio](https://github.com/tokio-rs/tokio) also supports them.  I suspect we can use it as inspiration for BSD [tests](https://github.com/tokio-rs/tokio/blob/master/.cirrus.yml) :-)

Regarding my [previous comment](https://github.com/EstebanBorai/local-ip-address/pull/87#issuecomment-1315120902), it appears they only test on FreeBSD (using Cirrus, as I [suggested](https://github.com/EstebanBorai/local-ip-address/pull/85#issuecomment-1312852325)), but still state support for OpenBSD, NetBSD, etc.

**Comment by EstebanBorai** [comment]
> By the way, while researching BSD-based operating systems that Rust supports, I found that [Tokio](https://github.com/tokio-rs/tokio) also supports them. I suspect we can use it as inspiration for BSD [tests](https://github.com/tokio-rs/tokio/blob/master/.cirrus.yml) :-)

Awesome! Nice finding @jakewilliami!

**Comment by EstebanBorai** [comment]
> Regarding my [previous comment](https://github.com/EstebanBorai/local-ip-address/pull/87#issuecomment-1315120902), it appears they only test on FreeBSD (using Cirrus, as I [suggested](https://github.com/EstebanBorai/local-ip-address/pull/85#issuecomment-1312852325)), but still state support for OpenBSD, NetBSD, etc.

I think we could follow the same path as well! If at some point we find any issues we could document them and fix them.
I also think its worth to explain this in the documentation for the compatibility table we have in the README. WDYT?

**Comment by jakewilliami** [comment]
> I also think its worth to explain this in the documentation for the compatibility table we have in the README. WDYT?
@EstebanBorai agreed!  Actioned via 3e7b3b5.

**Comment by jakewilliami** [comment]
If you're happy with this PR, and pipelines are passing, please feel free to merge.  I'll start work on the other two outstanding points in the coming days :-)

**Pull request merged**
