### PR TITLE
feat: freebsd support

### PR DESCRIPTION
**Pull request by EstebanBorai**
Integration to bring support for FreeBSD.

### CODE REVIEW

**Comment by EstebanBorai** [comment]
Hi @jakewilliami! As I see it we are good to go for BSD support in this PR!
Let me know if you plan to add something more, otherwise I merge this and publish later today!

Thanks for the support!

**Comment by jakewilliami** [comment]
Hi @EstebanBorai, this morning I started work on unit tests for FreeBSD, so maybe hold fire for a moment before merging!  I feel a little out of my depth (I’m not super familiar with Cirrus, nor Rust unit tests), but I’ll put something together in the next day or two, and ask what you think.  Then we can merge, I think :-)

**Comment by EstebanBorai** [comment]
> Hi @EstebanBorai, this morning I started work on unit tests for FreeBSD, so maybe hold fire for a moment before merging! I feel a little out of my depth (I’m not super familiar with Cirrus, nor Rust unit tests), but I’ll put something together in the next day or two, and ask what you think. Then we can merge, I think :-)

That's great! I will wait for that feature then!

**Comment by EstebanBorai** [comment]
@jakewilliami Cirrus will be working from this PR now! I just merged #92 so from now own we have Cirrus support thanks to you! Great work @jakewilliami!

**Comment by jakewilliami** [comment]
Thanks for your support @EstebanBorai!  If you’re happy with this, so am I.  Feel free to merge this into master, make a new release, tell Reddit, tell your friends, etc. etc. 😄

**Comment by EstebanBorai** [comment]
> Thanks for your support @EstebanBorai! If you’re happy with this, so am I. Feel free to merge this into master, make a new release, tell Reddit, tell your friends, etc. etc. 😄

Thanks to you @jakewilliami! I really appreciate the time and effort you put on this!

**Pull request merged**
